// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDO6aXL8GjM9uskUXs55IVZhMiDVxCgD7I',
    appId: '1:1023865318271:web:45674816a923b04c60084a',
    messagingSenderId: '1023865318271',
    projectId: 'vento-soffio',
    authDomain: 'vento-soffio.firebaseapp.com',
    storageBucket: 'vento-soffio.firebasestorage.app',
    measurementId: 'G-RYF5GKDRCT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUgNvZLurKTnw6AIie8hB8JqWiHdvvgIg',
    appId: '1:1023865318271:android:d6a095bd4de23f2c60084a',
    messagingSenderId: '1023865318271',
    projectId: 'vento-soffio',
    storageBucket: 'vento-soffio.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDoOxHYdMPZCnhtK8oWfRxFUvfhJkVwxqg',
    appId: '1:1023865318271:ios:891076a5b8a346e460084a',
    messagingSenderId: '1023865318271',
    projectId: 'vento-soffio',
    storageBucket: 'vento-soffio.firebasestorage.app',
    iosBundleId: 'com.example.ventoSoffio',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDoOxHYdMPZCnhtK8oWfRxFUvfhJkVwxqg',
    appId: '1:1023865318271:ios:891076a5b8a346e460084a',
    messagingSenderId: '1023865318271',
    projectId: 'vento-soffio',
    storageBucket: 'vento-soffio.firebasestorage.app',
    iosBundleId: 'com.example.ventoSoffio',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDO6aXL8GjM9uskUXs55IVZhMiDVxCgD7I',
    appId: '1:1023865318271:web:4ab05613b4997e6360084a',
    messagingSenderId: '1023865318271',
    projectId: 'vento-soffio',
    authDomain: 'vento-soffio.firebaseapp.com',
    storageBucket: 'vento-soffio.firebasestorage.app',
    measurementId: 'G-ZZRW4961SQ',
  );

}